### PR TITLE
Remove Contributing Guidelines from README.md, create another file instead.

### PR DESCRIPTION
**Pull request by KendallDoesCoding**

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@ThioJoe I can move the CONTRIBUTING.md file to .github if you like.

**Comment by KendallDoesCoding** [comment]
oops two of the same commit, sorry

**Comment by ThioJoe** [comment]
Nah, most people won't bother clicking through to it

**Comment by KendallDoesCoding** [comment]
> Nah, most people won't bother clicking through to it

Ok

**Pull request closed without merging**
