### PR TITLE
Changed order to be alphabetical

### PR DESCRIPTION
**Pull request by Firecul**
Helps users to find anything that might already exist easier.
Also exposed some duplicates

### CODE REVIEW

**Comment by Tyler887** [comment]
@ThioJoe There was no comments or a merge on this one, I suggest you merge it, because it improves readability.

**Comment by Firecul** [comment]
Don't know why GitHub didn't like that update commit it made me merge main even though I had done so myself but at least it works.

**Comment by ThioJoe** [comment]
Yea I'll consider this, only reason I might decide not to is because the way it is now, it's basically sorted by date, and might be worth dropping old names off at some point

**Comment by Firecul** [comment]
> might be worth dropping old names off at some point

If anyone registers a legit domain it could always be submitted as a false positive, unless someone will be manually checking each domain one by one to see if it's legit yet?

**Comment by KendallDoesCoding** [comment]
> > might be worth dropping old names off at some point
> 
> If anyone registers a legit domain it could always be submitted as a false positive, unless someone will be manually checking each domain one by one to see if it's legit yet?

Well, most of these scam domains keep weird end like .von .lol, etc. So 99% of the time noone will register it as a legit domain if it was once a scam domain, as per what I gage.

**Comment by KendallDoesCoding** [comment]
And half of these sites also have just weird things in the domain so I doubt people will register it as a legit domain, either way../

**Pull request closed without merging**
